config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'puzzle' => 'puzzles#show_puzzles'
  get 'tech' => 'puzzles#show_techs'

  get '/dashboard' => 'users#dashboard', as: :dashboard

  resources :user

  namespace :admin do
    get '/' => 'home#index', as: :dashboard

    post '/receivers/new' => 'receivers#create', as: :create_receiver
    get '/receivers/new' => 'receivers#new', as: :new_receiver
    get '/receivers/:id/edit' => 'receivers#edit', as: :edit_receiver
    get '/receivers/:id' => 'receivers#show', as: :receiver
    patch '/receivers/:id' => 'receivers#update', as: :update_receiver
    delete '/receivers/:id' => 'receivers#destroy', as: :destroy_receiver
    post '/receivers/gift' => 'receivers#gift', as: :gift_receiver
  end

end

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>One Small Step TM</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
 

</head>
<body>


<%= yield %>

</body>
</html>

app/views/layouts/application_admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(yield(:title)) %></title>
  <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"> -->
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> 
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script> 
  <%= render 'layouts/shim' %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top navbar-admin" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <%= link_to "One Small Step", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Admin Dashboard", admin_dashboard_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Switch&nbsp;<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "User Dashboard", dashboard_path %></li>
              <li class="divider"></li>
              <li><a href="/">Logout</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= render 'shared/notice_messages' %>
    <%= yield %>
    <hr>
    <footer>
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright &copy; One Small Step 2015.</p>
        </div>
      </div>
    </footer>
    
  </div>
</body>
</html>